require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'app/models/application_record.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ContextWording:
  Prefixes:
    - when
    - given

RSpec/ExampleLength:
  Max: 15
