apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: global-messages
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: global-messages
spec:
  params:
  - name: clusterBuilder
    value: full-jammy
  serviceClaims:
   - name: postgresql-global-messages
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: postgresql-global-messages
   - name: redis-global-messages
     ref:
       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
       kind: ClassClaim 
       name: redis-global-messages
  env:
   - name: SECRET_KEY_BASE
     valueFrom:
       secretKeyRef:
         name: rails-secret-key-trev-cluster
         key: SECRET_KEY_BASE
  source:
    git:      
      url: https://github.com/trevorputbrese/global-messages
      ref:
        branch: main
